# Generated by Django 3.1.7 on 2021-03-30 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
