# Generated by Django 3.1.7 on 2021-08-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='org',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='org_permision',
        ),
        migrations.AddField(
            model_name='user',
            name='organization_permission',
            field=models.CharField(choices=[('0', 'User'), ('9', 'Admin')], default=0, max_length=1, verbose_name='Acces level'),
        ),
    ]
