# Generated by Django 3.1.7 on 2021-08-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210822_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_permission',
            field=models.CharField(blank=True, choices=[('0', 'User'), ('9', 'Admin')], default=None, max_length=1, null=True, verbose_name='Acces level'),
        ),
    ]
