# Generated by Django 3.1.7 on 2021-08-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210809_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.organization'),
        ),
    ]
