# Generated by Django 3.1.7 on 2021-08-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210809_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='home.profile'),
        ),
    ]
