# Generated by Django 3.1.7 on 2021-08-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210813_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.organization'),
        ),
    ]
