# Generated by Django 3.1.7 on 2021-09-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.maintenance'),
        ),
    ]
