# Generated by Django 3.1.7 on 2021-09-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210903_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
