# Generated by Django 3.1.7 on 2021-09-16 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210906_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible'), ('ESTATE', 'Estate'), ('VAN', 'Van')], default='SEDAN', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.FloatField(default=1.4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('PETROL', 'Petrol'), ('BIO', 'BIO'), ('LPG', 'LPG'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='PETROL', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('USE', 'In Use'), ('OUT', 'Out of order'), ('SERVICE', 'Service')], default='USE', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(9999)]),
            preserve_default=False,
        ),
    ]
