# Generated by Django 3.1.7 on 2021-09-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210916_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Convertible', 'Convertible'), ('Estate', 'Estate'), ('VAN', 'VAN')], max_length=11),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('BIO', 'BIO'), ('LPG', 'LPG'), ('Diesel', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Out of order', 'Out of order'), ('Service', 'Service')], max_length=12),
        ),
    ]
