# Generated by Django 3.1.7 on 2021-10-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210916_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Convertible', 'Convertible'), ('Estate', 'Estate'), ('VAN', 'VAN'), ('Coupe', 'Coupe')], max_length=11),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('BIO', 'BIO'), ('LPG', 'LPG'), ('Diesel', 'Diesel'), ('ELECTRIC', 'Electric'), ('Hybrid', 'Hybrid')], max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('In use', 'In use'), ('Free', 'Free'), ('Broken', 'Broken'), ('Service', 'Service'), ('Transport', 'Transport')], max_length=12),
        ),
        migrations.CreateModel(
            name='CarPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
            ],
        ),
    ]
