# Generated by Django 3.1.7 on 2021-10-16 09:49

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211012_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='absload',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='alt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='colanttemp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='ctrlmodvoltage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='engineload',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='fuellevel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='fuelpressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='fuelrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='intakeairtemp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='kph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='mafrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='mainfoldpressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='oiltemp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='rpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='throttle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gps',
            name='torque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carpicture',
            name='file',
            field=models.FileField(upload_to=home.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='gps',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gps',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
