# Generated by Django 3.1.7 on 2021-10-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211017_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
