# Generated by Django 3.1.7 on 2021-10-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_cardrivershistory_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardrivershistory',
            old_name='mileage',
            new_name='start_mileage',
        ),
        migrations.AddField(
            model_name='cardrivershistory',
            name='end_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
