# Generated by Django 3.1.7 on 2021-11-11 17:53

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20211024_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDamages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=255)),
                ('guilty', models.CharField(max_length=255)),
                ('repaired', models.CharField(max_length=255)),
                ('insurance', models.CharField(max_length=255)),
                ('damages', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
                ('carservice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.carservice')),
            ],
        ),
        migrations.CreateModel(
            name='CarDamagesAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=home.models.get_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cardamages')),
            ],
        ),
    ]
