# Generated by Django 3.1.7 on 2021-11-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_cardamages_cardamagesattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardamages',
            old_name='carservice',
            new_name='shop',
        ),
    ]
