# Generated by Django 3.1.7 on 2021-11-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_reminders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminders',
            name='repetetive',
        ),
    ]
