# Generated by Django 3.1.7 on 2021-11-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_reminders_repetetive'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminders',
            name='task',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
