# Generated by Django 3.1.7 on 2021-11-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_reminders_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(default='XXX 0000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminders',
            name='when',
            field=models.DateTimeField(),
        ),
    ]
