# Generated by Django 3.1.7 on 2022-01-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pb95', models.CharField(max_length=3)),
                ('pb98', models.CharField(max_length=3)),
                ('on', models.CharField(max_length=3)),
                ('lpg', models.CharField(max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
