# Generated by Django 3.1.7 on 2022-01-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_fuelprices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelprices',
            old_name='date',
            new_name='reported',
        ),
    ]
